disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - force_cast

line_length: 160

type_body_length:
  - 300 # warning
  - 400 # error

identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - on
